In [1]:
# Import numpy.
import numpy as np

# Задание 1.

In [2]:
rev_arr = np.arange(9, -1, -1)
print(rev_arr)

[9 8 7 6 5 4 3 2 1 0]


# Задание 2.

In [3]:
matrix = np.diag(rev_arr)
print(matrix)
np.diagonal(matrix).sum()

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


45

# Задание 3.

In [4]:
vectors = [[4, 2, 1], [1, 3, 0], [0, 5, 4]]
values = [4, 12, -3]
answer = np.linalg.solve(vectors, values)
print(answer)

# Test.
np.allclose(np.dot(vectors, answer), values)

[ 0.46666667  3.84444444 -5.55555556]


True

# Задание 4.

In [5]:
# Shopping matrix.
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4],
    ], 
    np.int32
)

# New user.
next_user_stats = np.array([0, 1, 2, 0, 0, 0])


# Function for counting cosine.
def cosine(a, b):
    """
    Counts cosine of an angle between vectors a and b.
    """
    
    # Vectors length.
    aLength = np.linalg.norm(a)
    bLength = np.linalg.norm(b)
    
    return np.dot( a, b ) / ( aLength * bLength )


# Main block.
def main():
    closest = 0
    index = 0
    cosine_max = max([(num+1, cosine(next_user_stats, vect)) for num, vect in enumerate(users_stats)],
                    key=lambda elem: elem[1])
    return f'Ближайший пользователь под номером "{cosine_max[0]}".' +\
            f'Косинусное сходство: {cosine_max[1]:.2f}.'
    

print(main())

Ближайший пользователь под номером "8".Косинусное сходство: 0.95.
